sudo: required

services:
  - docker

before_script:
  - sudo /etc/init.d/mysql stop

script:
  # Start, wait 5 minutes, get logs, shut down
  - docker-compose up -d && sleep 5m && docker-compose logs golang-server && docker-compose logs golang-client && docker-compose down

notifications:
  email:
    on_failure: always

after_success:
  - cat ./src/Server/coverage.txt ./src/Client/coverage.txt >> go_coverage.txt
  - bash <(curl -s https://codecov.io/bash) -f go_coverage.txt
