sudo: required

env:
  global:
  - GO111MODULE=on

language: go
go:
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - 1.14.x
  - 1.15.x
  - tip

services:
  - docker

before_script:
  - sudo /etc/init.d/mysql stop

script:
  # Wait 10 minutes before shutting down
  - travis_wait docker-compose up --abort-on-container-exit --exit-code-from golang-client

notifications:
  email:
    on_failure: always

after_success:
  - bash <(curl -s https://codecov.io/bash)
