sudo: required

env:
  global:
  - GO111MODULE=on

language: go
go:
  - 1.15.x
  - tip

services:
  - docker

before_script:
  - sudo /etc/init.d/mysql stop

script:
  # Start, wait 5 minutes, get logs, shut down
  - docker-compose up -d && sleep 5m && docker-compose logs golang-server && docker-compose logs golang-client && docker-compose down

notifications:
  email:
    on_failure: always

after_success:
  - bash <(curl -s https://codecov.io/bash)
