env:
  global:
  - GO111MODULE=on

language: go
go:
  - 1.11.x
  - tip

services:
  - docker

before_script:
  - sudo /etc/init.d/mysql stop

script:
  - docker-compose up

notifications:
  email: false

after_success:
  - bash <(curl -s https://codecov.io/bash)
