env:
  global:
  - GO111MODULE=on

language: go
go:
  - 1.11.x
  - tip

services:
  - docker

before_script:
  - sudo /etc/init.d/mysql stop

script:
  # Wait 10 minutes before shutting down
  - travis_wait docker-compose up
  - docker-compose down

notifications:
  email:
    on_failure: always

after_success:
  - bash <(curl -s https://codecov.io/bash)
